using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Unity.Barracuda;
using RestrictionSystem;
using Sirenix.OdinInspector;
using System.Linq;
using System.IO;
using System;
using Unity.Mathematics;
using Athena;
using System.Diagnostics;
using Debug = UnityEngine.Debug;

//using untiy.mat



public class PythonTest : SerializedMonoBehaviour
{
    public static PythonTest instance;
    private void Awake() { instance = this; }
    
    private IWorker CheckWorker;

    [Range(1,20)]public int PrintDecimals = 5;

    public FinalMotion CalculatedMotion;

    //public bool UsePreprocessing;
    public bool DoExport;
    public int ExcelMotions;

    public bool RunAccuracyTest;


    public bool TrackEndOnly;

    public Athena.Athena A = Athena.Athena.instance;
    public Runtime R = Runtime.instance;
    public MotionEditor ME = MotionEditor.instance;

    //public List<int> AllActiveMotions { get { return Enumerable.Range(0, A.MotionCount()).Where(motion => MotionsToUse[motion]).ToList(); } }
    public string JSONDirectory { get {return Path.Combine(Path.GetDirectoryName(Application.dataPath), "WildfireLearning"); } }
    public string scriptPath { get { return Path.Combine(JSONDirectory, "DeepLearningModel.py"); } }
    private string pythonPath = "python"; // or "python3" for some systems
    
    [Button]public void RunPythonMachineLearning()
    {
        ProcessStartInfo start = new ProcessStartInfo();
        start.FileName = pythonPath;
        start.Arguments = string.Format("\"{0}\"", scriptPath);
        start.UseShellExecute = false; // Do not use OS shell
        start.CreateNoWindow = true; // We don't need a new window
        start.RedirectStandardOutput = true; // Any output, generated by application will be redirected back
        start.RedirectStandardError = true; // Any error in standard output will be redirected back

        using (Process process = Process.Start(start))
        {
            using (System.IO.StreamReader reader = process.StandardOutput)
            {
                string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")

                if (!string.IsNullOrEmpty(stderr))
                {
                    Debug.LogError("Python Error: " + stderr);
                }

                Debug.Log(result);
            }
        }
    }

    
    [Button]public void TestModel()
    {
        PythonTest.instance = this;
        CheckWorker = WorkerFactory.CreateWorker(WorkerFactory.Type.ComputePrecompiled, R.runtimeModel);
        
        float4 Guesses = float4.zero;


        List<float> FrameInputData = new List<float>();
        int TotalCount = 0;
        GuessLogging Logging = new GuessLogging();
        
        foreach (Spell SpellType in A.Movements.Keys)
        {
            //Debug.Log(SpellType);
            for (int i = 0; i < A.MovementCount(SpellType); i++)
            {
                for (int j = R.FramesAgoBuild; j < A.FrameCount(SpellType, i); j++)
                {
                     //Debug.Log("1: " + (j - FramesAgoBuild) + "  2: " + (j + 1));
                    //Debug.Log(Enumss[0] + "  " + Enumss[^1]);
                    //for (int l = 0; l < Enumss.Count; l++)
                        //Debug.Log(Enumss[l]);

                    List<AthenaFrame> AllInfos = Enumerable.Range(j - R.FramesAgoBuild, R.FramesAgoBuild).Select(x => A.AtFrameInfo(SpellType, i, x)).ToList();
                    List<float> Inputs = FrameToValues(AllInfos);


                    if (DoExport)
                    {
                        TotalCount++;
                        
                        //Debug.Log("TotalCount: " + TotalCount + " SpellType: " + SpellType + "  Movement: " + i + "  TopFrame: " + j);
                        if (TotalCount < ExcelMotions)
                        {
                            for (int x = 0; x < Inputs.Count; x++)
                            {
                                FrameInputData.Add(Inputs[x]);
                                //debugString += " 'Inputs[" + x + "]':" + Inputs[x].ToString("f3");
                            }
                        }
                       
                        
                    }
                    if (RunAccuracyTest)
                    {
                        bool IsTrue = A.FrameWorks(SpellType, i, j) && SpellType == ME.MotionType;
                        bool Guess = R.PredictState(Inputs);
                        bool Correct = Guess == IsTrue;
                        Logging.UpdateGuesses(Correct, IsTrue);
                    }
                }
            }
        }

        /*
        ///testing:
        for (int m = 0; m < CalculatedMotion.Motions.Count; m++)
        {
            //Debug.Log(SpellType);
            for (int f = FramesAgoBuild - 1; f < CalculatedMotion.Motions[m].Frames.Count; f++)
            {
                List<float> InvolvedInputs = new List<float>();
                for (int k = f - FramesAgoBuild + 1; k <= f; k++)
                {
                    Debug.Log(k + " of " + f);
                    InvolvedInputs.AddRange(CalculatedMotion.Motions[m].Frames[k].InputList());
                }
                Debug.Log(InvolvedInputs.Count);
                if (RunAccuracyTest)
                {
                    bool IsTrue = CalculatedMotion.Motions[m].Frames[f].Active;

                    bool Guess = PredictState(InvolvedInputs);
                    bool Correct = Guess == IsTrue;
                    Logging.UpdateGuesses(Correct, IsTrue);
                }

            }
        }
        */

        //Debug.Log(FrameInputData.Count);
        if (DoExport)
            SpreadSheet.OutputExcelInfo(FrameInputData.ToArray());

        if (RunAccuracyTest)
            Debug.Log(Logging.PercentSimpleString());
            Debug.Log(Logging.GuessCountString());
            Debug.Log(Logging.MotionCountString());
            Debug.Log(Logging.OutcomesCountString());
            Debug.Log(Logging.PercentComplexString());
    }

    public List<float> FrameToValues(List<AthenaFrame> Frames)
    {
        //List<float> FrameInputs = Frames.SelectMany(x => x.AsInputs()).ToList();
        List<float> FrameInputs = Frames.SelectMany(x => x.AsInputs()).ToList();
        FrameInputs = FrameInputs.Select(x => MathF.Round(x, PrintDecimals)).ToList();
        return FrameInputs;
    }

    public FinalMotion GetAllMotionList(Spell spell)
    {
        List<Motion> ReturnList = new List<Motion>();

        foreach(Spell SpellType in A.Movements.Keys)
        {
            bool CanBeTrue = spell == SpellType;
            foreach(AthenaMotion motion in A.Movements[SpellType].Motions)
            {
                List<Frame> frames = new List<Frame>();
                for (int j = 0; j < motion.Infos.Count; j++)
                {
                    AthenaFrame info = motion.Infos[j];
                    bool State = motion.AtFrameState(j) && CanBeTrue;

                    List<float> FramesInfo = FrameToValues(new List<AthenaFrame>() { info });

                    frames.Add(new Frame(FramesInfo.ToArray(), State));
                }
                ReturnList.Add(new Motion(frames));
            }
            
        }

        return new FinalMotion(ReturnList);
    }

    
    [Button]public void ReloadJSON()
    {
        ReloadJSONType(GameObject.FindObjectOfType<MotionEditor>().MotionType);
        //RunPythonScript.ExecutePythonScript(JSONDirectory + "/DeepLearningModel.py");
    }
    public void ReloadJSONType(Spell spell)
    {
        PythonTest.instance = this;
        CalculatedMotion = GetAllMotionList(spell);
        string directory = Path.Combine(JSONDirectory, spell.ToString() + ".json");
        
        // Convert the ScriptableObject to a JSON string
        string json = JsonUtility.ToJson(CalculatedMotion);

        // Write the JSON string to a file
        File.WriteAllText(directory, json);
    }
    
    [System.Serializable]public class FinalMotion
    {
        [ListDrawerSettings(ShowIndexLabels = true)]public List<Motion> Motions;
        public FinalMotion(List<Motion> Motions)
        {
            this.Motions = Motions;
        }
    }
    [System.Serializable]public class Motion
    {
        [ListDrawerSettings(ShowIndexLabels = true)] public List<Frame> Frames;
        public Motion(List<Frame> Frames)
        {
            this.Frames = Frames;
        }
    }
    [System.Serializable]public class Frame
    {
        public string[] FrameInfo;
        public bool Active;


        /*
        public AthenaFrame info;
        public float TimeSinceLast;
        public Frame(AthenaFrame info, bool Active, float TimeSinceLast)
        {
            this.info = info;
            this.Active = Active;
            this.TimeSinceLast = TimeSinceLast;
        }
        */

        public Frame(float[] FrameInfo, bool Active)
        {
            List<float> RealFrameInfo = FrameInfo.ToList();
            
            this.FrameInfo = RealFrameInfo.Select(x => x.ToString()).ToArray();
            this.Active = Active;
            
        }

        public List<float> InputList()
        {
            List<float> newList = FrameInfo.Select(x => float.Parse(x)).ToList();
            //newList.Add(float.Parse(Time));
            return newList;
        }
    }



    ///pass values
}
public struct GuessLogging
{
    public void UpdateGuesses(bool Correct, bool IsTrue)
    {
        Guesses.w += (Correct && IsTrue) ? 1f : 0f;
        Guesses.x += (!Correct && IsTrue) ? 1f : 0f;
        Guesses.y += (Correct && !IsTrue) ? 1f : 0f;
        Guesses.z += (!Correct && !IsTrue) ? 1f : 0f;
    }

    public float4 Guesses;
    public GuessLogging(float4 Guesses)
    {
        this.Guesses = Guesses;
    }
    public float Total() { return Guesses.w + Guesses.x + Guesses.y + Guesses.z; }
    public string PercentComplexString() { return "Correct: " + CorrectPercent() + "  Wrong: " + InCorrectPercent() + "  True: " + OnTruePercent() + "  False: " + OnFalsePercent(); }
    public string PercentSimpleString() { return "CorrectOnTrue: " + CorrectOnTruePercent() + "/" + IncorrectOnTruePercent() + "   CorrectOnFalse: " + CorrectOnFalsePercent() + "/" + IncorrectOnFalsePercent(); }

    //public string CorrectPercentString() { return "CorrectOnTrue/Incorrect%: " + } 

    public string MotionCountString() { return "True/False Frames: " + CorrectOnTrue() + IncorrectOnTrue() + "/" + CorrectOnFalse() +IncorrectOnFalse(); }
    public string GuessCountString() { return "True/False Guesses: " + CorrectOnTrue() + IncorrectOnFalse() + "/" + CorrectOnFalse() + IncorrectOnTrue(); }
    public string OutcomesCountString() { return "CorrectOnTrue: " + CorrectOnTrue() + "  IncorrectOnTrue: " + IncorrectOnTrue() + "  CorrectOnFalse: " + CorrectOnFalse() + "  IncorrectOnFalse: " + IncorrectOnFalse(); }

    public float CorrectOnTrue() { return Guesses.w; }
    public float IncorrectOnTrue() { return Guesses.x; }
    public float CorrectOnFalse() { return Guesses.y; }
    public float IncorrectOnFalse() { return Guesses.z; }

    public float CorrectOnTruePercent() { return CorrectOnTrue() / (CorrectOnTrue() + IncorrectOnTrue()) * 100f; }
    public float IncorrectOnTruePercent() { return IncorrectOnTrue() / (CorrectOnTrue() + IncorrectOnTrue()) * 100f; }
    public float CorrectOnFalsePercent() { return CorrectOnFalse() / (CorrectOnFalse() + IncorrectOnFalse()) * 100f; }
    public float IncorrectOnFalsePercent() { return IncorrectOnFalse() / (CorrectOnFalse() + IncorrectOnFalse()) * 100f; }


    public float CorrectPercent() { return (CorrectOnTrue() + CorrectOnFalse()) / Total() * 100f; }
    public float InCorrectPercent() { return (IncorrectOnTrue() + IncorrectOnFalse()) / Total() * 100f; }
    public float OnTruePercent() { return (CorrectOnTrue() + IncorrectOnTrue()) / Total() * 100f; }
    public float OnFalsePercent() { return (CorrectOnFalse() + IncorrectOnFalse()) / Total() * 100f; }
}